name: Run tests

on:
  pull_request:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo 
        uses: actions/checkout@v4
      - name: Enforce formatting
        run: cargo fmt --check

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo 
      uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose